# Generated by Django 5.2.4 on 2025-08-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clock_speed_ghz', models.FloatField()),
                ('core_count', models.IntegerField()),
                ('thread_count', models.IntegerField()),
                ('cache_size_l1', models.IntegerField()),
                ('cache_size_l2', models.IntegerField()),
                ('cache_size_l3', models.IntegerField()),
                ('tdp_watts', models.IntegerField()),
                ('architecture_generation', models.CharField(max_length=255)),
                ('ipc', models.FloatField(help_text='Instructions per clock')),
            ],
        ),
    ]
