# Generated by Django 5.2.4 on 2025-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vram_gb', models.FloatField()),
                ('core_count', models.IntegerField()),
                ('core_clock_ghz', models.FloatField()),
                ('memory_bandwidth_gbps', models.FloatField()),
                ('architecture', models.CharField(max_length=255)),
                ('ray_tracing_support', models.BooleanField(default=False)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
