# Generated by Django 5.2.4 on 2025-08-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_need'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Need',
        ),
    ]
