# Generated by Django 5.2.4 on 2025-08-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size_gb', models.IntegerField()),
                ('speed_mhz', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
