# Generated by Django 5.2.4 on 2025-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsCoefficients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='phones_images/')),
                ('ram_size', models.IntegerField(blank=True, null=True)),
                ('memory_size', models.IntegerField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('os_type', models.CharField(blank=True, max_length=255, null=True)),
                ('graphic_processor', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_mp', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=255, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
